var annotated_dup =
[
    [ "Syft", null, [
      [ "Build a DFA from a LTLf formula", "p02_api_example_dfa_representation.html#autotoc_md17", null ],
      [ "Explicit DFA representation (MONA-based)", "p02_api_example_dfa_representation.html#autotoc_md18", null ],
      [ "Explicit DFA representation (ADD-based)", "p02_api_example_dfa_representation.html#autotoc_md19", null ],
      [ "Symbolic DFA representation", "p02_api_example_dfa_representation.html#autotoc_md20", null ],
      [ "Printer", "classSyft_1_1Printer.html", "classSyft_1_1Printer" ],
      [ "BaseRunner", "classSyft_1_1BaseRunner.html", "classSyft_1_1BaseRunner" ],
      [ "FairnessRunner", "classSyft_1_1FairnessRunner.html", "classSyft_1_1FairnessRunner" ],
      [ "GR1Runner", "classSyft_1_1GR1Runner.html", "classSyft_1_1GR1Runner" ],
      [ "MaxSetRunner", "classSyft_1_1MaxSetRunner.html", "classSyft_1_1MaxSetRunner" ],
      [ "StabilityRunner", "classSyft_1_1StabilityRunner.html", "classSyft_1_1StabilityRunner" ],
      [ "SynthesisRunner", "classSyft_1_1SynthesisRunner.html", "classSyft_1_1SynthesisRunner" ],
      [ "Parser", "classSyft_1_1Parser.html", "classSyft_1_1Parser" ],
      [ "ExplicitStateDfa", "classSyft_1_1ExplicitStateDfa.html", "classSyft_1_1ExplicitStateDfa" ],
      [ "ExplicitStateDfaAdd", "classSyft_1_1ExplicitStateDfaAdd.html", "classSyft_1_1ExplicitStateDfaAdd" ],
      [ "SymbolicStateDfa", "classSyft_1_1SymbolicStateDfa.html", "classSyft_1_1SymbolicStateDfa" ],
      [ "BuchiReachability", "classSyft_1_1BuchiReachability.html", "classSyft_1_1BuchiReachability" ],
      [ "coBuchiReachability", "classSyft_1_1coBuchiReachability.html", "classSyft_1_1coBuchiReachability" ],
      [ "coGR1Reachability", "classSyft_1_1coGR1Reachability.html", "classSyft_1_1coGR1Reachability" ],
      [ "DfaGameSynthesizer", "classSyft_1_1DfaGameSynthesizer.html", "classSyft_1_1DfaGameSynthesizer" ],
      [ "InputOutputPartition", "classSyft_1_1InputOutputPartition.html", "classSyft_1_1InputOutputPartition" ],
      [ "Quantification", "classSyft_1_1Quantification.html", "classSyft_1_1Quantification" ],
      [ "NoQuantification", "classSyft_1_1NoQuantification.html", "classSyft_1_1NoQuantification" ],
      [ "Forall", "classSyft_1_1Forall.html", "classSyft_1_1Forall" ],
      [ "Exists", "classSyft_1_1Exists.html", "classSyft_1_1Exists" ],
      [ "ForallExists", "classSyft_1_1ForallExists.html", "classSyft_1_1ForallExists" ],
      [ "ExistsForall", "classSyft_1_1ExistsForall.html", "classSyft_1_1ExistsForall" ],
      [ "Reachability", "classSyft_1_1Reachability.html", "classSyft_1_1Reachability" ],
      [ "ReachabilityMaxSet", "classSyft_1_1ReachabilityMaxSet.html", "classSyft_1_1ReachabilityMaxSet" ],
      [ "Transducer", "classSyft_1_1Transducer.html", "classSyft_1_1Transducer" ],
      [ "GR1", "structSyft_1_1GR1.html", "structSyft_1_1GR1" ],
      [ "SmtOneStepRealizabilityVisitor", "classSyft_1_1SmtOneStepRealizabilityVisitor.html", "classSyft_1_1SmtOneStepRealizabilityVisitor" ],
      [ "SmtOneStepUnrealizabilityVisitor", "classSyft_1_1SmtOneStepUnrealizabilityVisitor.html", "classSyft_1_1SmtOneStepUnrealizabilityVisitor" ],
      [ "Stopwatch", "classSyft_1_1Stopwatch.html", "classSyft_1_1Stopwatch" ],
      [ "FairnessLtlfSynthesizer", "classSyft_1_1FairnessLtlfSynthesizer.html", "classSyft_1_1FairnessLtlfSynthesizer" ],
      [ "GR1LTLfSynthesizer", "classSyft_1_1GR1LTLfSynthesizer.html", "classSyft_1_1GR1LTLfSynthesizer" ],
      [ "LTLfMaxSetSynthesizer", "classSyft_1_1LTLfMaxSetSynthesizer.html", "classSyft_1_1LTLfMaxSetSynthesizer" ],
      [ "LTLfSynthesizer", "classSyft_1_1LTLfSynthesizer.html", "classSyft_1_1LTLfSynthesizer" ],
      [ "StabilityLtlfSynthesizer", "classSyft_1_1StabilityLtlfSynthesizer.html", "classSyft_1_1StabilityLtlfSynthesizer" ],
      [ "SynthesisResult", "structSyft_1_1SynthesisResult.html", "structSyft_1_1SynthesisResult" ],
      [ "MaxSetSynthesisResult", "structSyft_1_1MaxSetSynthesisResult.html", "structSyft_1_1MaxSetSynthesisResult" ],
      [ "OneStepSynthesisResult", "structSyft_1_1OneStepSynthesisResult.html", "structSyft_1_1OneStepSynthesisResult" ],
      [ "Synthesizer", "classSyft_1_1Synthesizer.html", "classSyft_1_1Synthesizer" ],
      [ "TLSFArgs", "structSyft_1_1TLSFArgs.html", "structSyft_1_1TLSFArgs" ],
      [ "VarMgr", "classSyft_1_1VarMgr.html", "classSyft_1_1VarMgr" ]
    ] ]
];